---
speed_stop:				128

rot_max_speed:			60
rot_med_speed:			48
rot_slow_speed:			20
rot_crawl_speed:		12

pos_max_speed:			75
pos_med_speed:			60
pos_slow_speed:			20
pos_crawl_speed:		12

slowdown_max_dist:		300
slowdown_med_dist:		150

slowdown_max_rot:		90
slowdown_med_rot:		45
slowdown_slow_rot:		15

rotation_close_enough:	0.5
position_close_enough:	2.5



max_enc_incr:			980
max_enc_diff:			440
too_long:				20

xres:					30000
yres:					20000

encoder_resolution:		980
wheelbase:				300
wheel_radius: 			102

encoder_constant:		0.327
dist_per_tick:			0.382
enc_per_degree: 		8.0
slippage_constant: 		1.02
max_wait:				2000
...