---
pos_speed_max_pos: 		215
pos_speed_med_pos:		185
pos_speed_slow_pos:		148
pos_speed_slow_neg:		108
pos_speed_med_neg:		70
pos_speed_max_neg:		40

rot_speed_max_pos: 		205
rot_speed_med_pos:		175
rot_speed_slow_pos:		148
rot_speed_slow_neg:		108
rot_speed_med_neg:		80
rot_speed_max_neg:		50

speed_stop:				128

slowdown_max_dist:		300
slowdown_med_dist:		150
slowdown_max_rot:		70
slowdown_med_rot:		40

rotation_close_enough:	0.8
position_close_enough:	3.0

max_enc_incr:			980
max_enc_diff:			440
too_long:				20

xres:					30000
yres:					20000

encoder_resolution:		980
wheelbase:				300
wheel_radius: 			102

encoder_constant:		0.327
dist_per_tick:			0.382
enc_per_degree: 		8.0
slippage_constant: 		1.02
max_wait:				2000
...