---
SPEED_MAX_NEG: 			225
SPEED_MED_NEG:			192
SPEED_SLOW_NEG:			150
SPEED_STOP:				128
SPEED_SLOW_POS:			106
SPEED_MED_POS:			64
SPEED_MAX_POS:			30

SLOWDOWN_MAX_DIST:		120
SLOWDOWN_MED_DIST:		60
SLOWDOWN_DISTANCE_ROT:	10

ROTATION_CLOSE_ENOUGH:	1.0
POSITION_CLOSE_ENOUGH:	2.0

MAX_ENC_INCR:			980

MAX_ENC_DIFF:			440
TOO_LONG:				20

XRES:					30000
YRES:					20000

ENCODER_CONSTANT:		0.327
DIST_PER_TICK:			0.382
MAX_WAIT:				2000




...