---
pos_speed_max_pos: 		235
pos_speed_med_pos:		192
pos_speed_slow_pos:		150
pos_speed_slow_neg:		106
pos_speed_med_neg:		64
pos_speed_max_neg:		20

rot_speed_max_pos: 		225
rot_speed_med_pos:		192
rot_speed_slow_pos:		140
rot_speed_slow_neg:		116
rot_speed_med_neg:		64
rot_speed_max_neg:		30

speed_stop:				128

slowdown_max_dist:		60
slowdown_med_dist:		30
slowdown_max_rot:		70
slowdown_med_rot:		40

rotation_close_enough:	1.0
position_close_enough:	5.0

max_enc_incr:			980
max_enc_diff:			440
too_long:				20

xres:					30000
yres:					20000

encoder_resolution:		980
wheelbase:				300
wheel_radius: 			102

encoder_constant:		0.327
dist_per_tick:			0.382
enc_per_degree: 		8.32
slippage_constant: 		1.02
max_wait:				2000
...